### ISSUE TITLE
Converting data for phy

### ISSUE THREAD

**Issue by jonnew** [kylerbrown/openephys#1]
I was able to use `kwik2dat.py` to convert an OE `.kde` file, but phy does not seem to like this file. Its complaining about the extension not being `.kwik`. When I change the extension, I get

> An error has occurred (OSError): Unable to open file (File signature not found)

How are you using this script to create/load data into phy? Also, what is meant by phy? Are we talking about the GUI, or the programming interface for using with an Ipython notebook for instance.

**Comment by jonnew** [comment]
And here's the answer for everyone: read the manual :)

http://klusta.readthedocs.org/en/latest/#using-the-gui

**Comment by jonnew** [comment]
OK, I'm becoming both more and less confused at the same time. It seems that phys, kusta, and klusta2 are all related projects but have slightly different workflows. I don't fully understand whats going on there, but in any case, I'm going to reopen this issue because I cannot seem to load the data file into any of these options yet. `klusta` expects a `.prm' parameter file and the`.dat`file to exist in the same directory or something. phy seems to work on the`.kwik` files produced by klusta, but I'm not sure. Anyway, If you could provide and example workflow for getting OE data to one of these tools, I would really appreciate it.

**Comment by kylerbrown** [comment]
Hi Jon,

Yes, the kwik/kwik2/phy world seems to have gone through a few different requirements for _both_ the .prm file and the raw data.

At one point the OE kwik format was designed to work with klustakwik, but I don't know which version (that would be useful info!). Since then klustakwik/phy has switched back to raw binary for the data, and the parameters in the .prm have evolved over time.

I have a tremendous amount of respect for the Klusta team, but I no longer use klustakwik/phy because of the rapid changes in the formats and the lagging documentation. If you are able to figure out a workflow, let me know! :smile: The .dat files should work fine, it's just a matter of getting the .prm file correct. My attempt at the .prm file generation is [here](https://github.com/kylerbrown/openephys/blob/master/openephys/klustafiles.py). Possibly we need to make different .prm files for different versions of klusta*/phy.

Instead I use [Spyking Circus ](http://spyking-circus.readthedocs.org/en/latest/). It is also an experimental piece of software, but I've found it to be stable and easy to use. And I know kwik2dat.py works with spyking circus. 

Keep me updated on your spike-sorting quest! It would be excellent if the OE community had a well documented spike-sorting path.

Cheers!

**Comment by kylerbrown** [comment]
I've added some spyking circus documentation. Hope that's helpful.

**Comment by jonnew** [comment]
yes, extremely. Thank you, Kyler :)

On Tue, Apr 19, 2016 at 2:38 PM, Kyler Brown notifications@github.com
wrote:

> I've added some spyking circus documentation. Hope that's helpful.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/kylerbrown/openephys/issues/1#issuecomment-212062338

## 

Jonathan Newman
Postdoctoral Fellow, MIT
http://www.mit.edu/~jpnewman/
